public class checkDataTypes {
    public void MethodBoolean(){
        boolean checkBlooen = true;
        system.debug(checkBlooen);
    }
    public void MethodInteger(){
        integer varfirst = 1;
        integer varsecond = 2;
        system.debug(varfirst);
        system.debug(varsecond);
    }
    public void StringMethod(){
        string varname = 'Name';
        string var2name = 'Hande';
        system.debug(varname);
        system.debug(var2name);
    }
}
