public class DataTypesPractice {
    public void dataMethod(){
        string inLove = 'Yunus';
        boolean lovesHande = true;
        integer anniversary = 11072010;
        integer howManyYears = 12;
        string lover = 'Hande';
        system.debug(inLove);
        system.debug(lovesHande);
        system.debug(anniversary);
        system.debug(lover);
        system.debug(howManyYears); 
    }
}
