public class PrimitiveData_Assignment {
    public void primitiveDataAssignmentMethod() {
        Id id1 = 'a0H8b00000nykG4EAI';
        String idBelongs = 'The following ID belongs to an Employee'; 
        Boolean isTrue = true;
        system.debug(id1);
        system.debug(idBelongs);
        system.debug(isTrue);
        system.debug('Display all 3 variables in a single line:  ' + id1 + ' ,' + idBelongs + ' and ' + isTrue);
    }
}
